export const TAB_HEIGHT = 50

export const NSLineBreakByWordWrapping = 0
export const NSLineBreakByCharWrapping = 1

export const initialSettings = {
    commonFontSize: 16,
    previewFontSize: 12,
    previewTheme: 'arduino-light',
    previewLineBreakMode: 0,
    historySort: 0,
    hideMethodsInheritedFromNSObject: true
}

export const previewThemes = [
    'a11y-dark',
    'a11y-light',
    'agate',
    'an-old-hope',
    'androidstudio',
    'arduino-light',
    'arta',
    // 'ascetic',
    'atelier-cave-dark',
    'atelier-cave-light',
    'atelier-dune-dark',
    'atelier-dune-light',
    'atelier-estuary-dark',
    'atelier-estuary-light',
    'atelier-forest-dark',
    'atelier-forest-light',
    'atelier-heath-dark',
    'atelier-heath-light',
    'atelier-lakeside-dark',
    'atelier-lakeside-light',
    'atelier-plateau-dark',
    'atelier-plateau-light',
    'atelier-savanna-dark',
    'atelier-savanna-light',
    'atelier-seaside-dark',
    'atelier-seaside-light',
    'atom-one-dark',
    'atom-one-light',
    'codepen-embed',
    'color-brewer',
    'darcula',
    'dark',
    'default',
    'docco',
    'dracula',
    'far',
    'foundation',
    'github-gist',
    'github',
    // 'gml',
    'googlecode',
    'grayscale',
    'gruvbox-dark',
    'gruvbox-light',
    'hopscotch',
    'hybrid',
    // 'idea',
    'ir-black',
    // 'isbl-editor-dark',
    // 'isbl-editor-light',
    'kimbie.dark',
    'kimbie.light',
    'lightfair',
    'magula',
    'mono-blue',
    'monokai-sublime',
    'monokai',
    'night-owl',
    'nord',
    'obsidian',
    'ocean',
    'paraiso-dark',
    'paraiso-light',
    // 'purebasic',
    // 'qtcreator_dark',
    // 'qtcreator_light',
    'railscasts',
    'rainbow',
    'routeros',
    'shades-of-purple',
    'solarized-dark',
    'solarized-light',
    'sunburst',
    'tomorrow-night',
    'tomorrow',
    'vs',
    'vs2015',
    'xcode',
    'xt256',
    'zenburn'
]
