# author:Levi
# 搭配convert_js_to_plugin.py使用。可将qx的js/conf/snippet文件转换为plugin文件。

name: convert_js_to_plugin

on: # 注释内容默认关闭，如单一使用工作流取消#并删除工作流最后一部分即可
 # push:
   # paths:
     # - 'scripts/**' 
 # pull_request:
   # paths:
     # - 'Loon/**' 
  workflow_dispatch: # 这是手动触发

jobs:
  generate_plugin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub

      - name: Run script
        run: python .github/scripts/convert_js_to_plugin.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: plugin-artifacts
          path: ${{ github.workspace }}/Loon

      - name: Check for changes
        id: check_changes
        run: |
          git status
          git diff-index --quiet HEAD || echo "::set-output name=changes_exist::true"
    
      - name: Commit and push if changes exist
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "自动更新：已转换为plugin文件"
          git push origin HEAD:main --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Trigger next workflow convert_js_to_stoverride
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: convert_js_to_stoverride.yml
          token: ${{ secrets.GITHUB_TOKEN }}    
